name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint --ext .jsx,.js src/
